name: Release

on:
  push:
    branches:
      - main
    paths:
      - 'apps/web/**'
      - 'package.json'
      - '.github/workflows/release.yml'
  workflow_dispatch:

permissions:
  contents: write

jobs:
  build:
    uses: BLAKE0709/atlas-pipeline-os/.github/workflows/reusable-build.yml@main
    with:
      working_directory: apps/web

  deploy:
    needs: build
    uses: BLAKE0709/atlas-pipeline-os/.github/workflows/reusable-release.yml@main
    with:
      working_directory: apps/web
      alias_domains: blinkwell.vercel.app
    secrets:
      VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
      VERCEL_ORG_ID: ${{ secrets.VERCEL_ORG_ID }}
      VERCEL_PROJECT_ID: ${{ secrets.VERCEL_PROJECT_ID }}
